import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Navbar from "../components/Navbar";
import SectionCards from "../components/SectionCards";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar username="Munir Mahmud" />
        <Banner
          title="Don't Lookup"
          subTitle="This is lovable movie"
          imgUrl="/assets/banner.jpg"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title="Movie Card" />
        </div>
        <div className={styles.sectionWrapper}>
          <SectionCards title="Desney" />
        </div>
        <div className={styles.sectionWrapper}>
          <SectionCards title="Watch Again" />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
